version: '3.9'

services:
  app:
    build:
      context: .
    image: expense_manager_web
    command: >
      sh -c "cd app &&
             python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py loaddata core/fixtures/default_category.json &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
      - ./data/web:/vol/web
    env_file: .env
    depends_on:
      - db
      - redis

  db:
    image: postgres:13-alpine
    env_file: .env

  redis:
    image: redis:7-alpine

  celery_worker:
    build:
      context: .
    image: expense_manager_celery_worker
    command: >
      sh -c ". ./celery/start-celeryworker"
    volumes:
      - ./app:/app
    env_file: .env
    depends_on:
      - db
      - redis

  celery_beat:
    build:
      context: .
    image: expense_manager_celery_beat
    command: >
      sh -c ". ./celery/start-celerybeat"
    volumes:
      - ./app:/app
    env_file: .env
    depends_on:
      - db
      - redis
