# Generated by Django 4.1.3 on 2022-12-01 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_expensemanageruser_alter_category_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expensemanageruser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelTable(
            name='expensemanageruser',
            table=None,
        ),
    ]
